name: ECS Pipeline Deployment
description: Updates a ECS service
author: https://github.com/Negotiatus
requirements:
  - aws
configuration:
  properties:
    workspace:
      type: string
    account_id:
      type: string
  additionalProperties: false
  required:
    - workspace
    - account_id