name: ECS Pipeline Deployment
description: Annotates the build with a file count
author: https://github.com/Negotiatus
requirements: []
configuration:
  properties:
    workspace:
      type: string
    account_id:
      type: string
  additionalProperties: false