name: ECS Pipeline Deployment
description: Updates a ECS service
author: https://github.com/Negotiatus
requirements:
  - aws
configuration:
  properties:
    account_id:
      type: string
    environment:
      type: string      
    service:
      type: string
    role:
      type: string
    deploy_tag:
      type: string
    docker_registry:
      type: string
    url:
      type: string
  additionalProperties: false
  required:
    - account_id
    - environment
    - service
    - role
    - deploy_tag
    - docker_registry
    - url