name: ECS Pipeline Deployment
description: Updates a ECS service
author: https://github.com/Negotiatus
requirements:
  - aws
configuration:
  properties:
    full_deployment:
      type: boolean
    workspace:
      type: string
    account_id:
      type: string
    docker_registry:
      type: string      
  additionalProperties: false
  required:
    - workspace
    - account_id
    - docker_registry
    - full_deployment