#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $SCRIPT_DIR/common.sh

set -e

WORKSPACE="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_WORKSPACE"
ACCOUNT_ID="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_ACCOUNT_ID"

if [[ $BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_FULL_DEPLOYMENT == true ]]; then
    echo "--- :rocket: :ecs: :ecr: Getting ECR images and restarting the services"
    ./deploy.sh
else
    echo "--- :rocket: :ecs: Restarting Services ..."
    AWS_PROFILE=`aws_assume_role BuildkiteDeploy $ACCOUNT_ID` || (echo "$AWS_PROFILE" && exit 1)
    ./restart_services.sh $WORKSPACE $AWS_PROFILE
fi