#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $SCRIPT_DIR/functions.sh

set -e

ENVIRONMENT="$1"
ACCOUNT_ID="$2"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DEPLOY_TAG="$3"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_ROLE="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_ROLE"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_SERVICE="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_SERVICE"
IMAGE="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DOCKER_REGISTRY/$APPLICATION:$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DEPLOY_TAG"

# For testing
ENVIRONMENT="sandbox"
ACCOUNT_ID="207628655394"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_ROLE="BuildkiteDeploy"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_SERVICE="assistant-sandbox"
APPLICATION="assistant"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DEPLOY_TAG="deploy-acc0954b8aafff22a79b2dc1fe435410593ee53b"
BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DOCKER_REGISTRY="247896140244.dkr.ecr.us-east-1.amazonaws.com"
IMAGE="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DOCKER_REGISTRY/$APPLICATION:$ENVIRONMENT"
TAG="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_DEPLOY_TAG"



echo "--- :aws-iam: Assuming $BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_ROLE role on $ENVIRONMENT ($ACCOUNT_ID)"
export AWS_PROFILE=deploy 
AWS_PROFILE=`aws_assume_role $BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_ROLE $ACCOUNT_ID` || (echo "$AWS_PROFILE" && exit 1)
CLUSTER="$BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_SERVICE"

echo "--- :ecs: Getting ECS service list for '$CLUSTER'"
SERVICES=`list_ecs_services $CLUSTER` || (echo "$SERVICES" && exit 1)
echo "Found `echo \"$SERVICES\" | wc -w | awk '{print $1}'` services:"
echo "$SERVICES" | tr '\t' '\n'
for service in $SERVICES; do
    service_name=`echo $service | cut -d/ -f3`
    ecs deploy $CLUSTER $service --image $service_name $IMAGE --health-check $service_name "curl -f $BUILDKITE_PLUGIN_ECS_PIPELINE_DEPLOYMENT_URL" 30 5 3 0
done